#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HW_03___Prospective_MDC_Student_App.Resource", IsApplication=true)]

namespace HW_03___Prospective_MDC_Student_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int campus_array = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int campus_directions = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int campus_phones = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Hialeah_Campus_2C_H = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Homestead_Campus_2C_H = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int InterAmerican_Campus_2C_H = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Kendall_Campus_2C_H = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MDC_Blue_H = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mdc_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Medical_Campus_2C_H = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int North_Campus_2C_H = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int West_Campus_2C_H = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Wolfson_Campus_2C_H = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnCall = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btnDirections = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int btnSubmit = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int imgMDCLogo = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int spnCampuses = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int txtMajor = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int txtName = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int displayCampus = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
